export const HEADINGS = {
  APP_TITLE: "SyncPad",
  APP_VERSION: "v1.0",
  AUTH: {
    LOGIN_TITLE: "SyncPad Login",
    REGISTER_TITLE: "SyncPad Register",
    SUBTITLE: "Seamless cross-device clipboard sync",
    LOADING: "Restoring session...",
  },
  LANDING: {
    TITLE: "Welcome to SyncPad",
    DESCRIPTION:
      "You do not belong to any workspace yet. Please contact your workspace administrator or maintainer to invite you to a workspace.",
  },
  DASHBOARD: {
    LIVE_SHEET_TAB: "⚡ Live Sheet",
    INITIALIZING_LIVE: "Initializing Live Space...",
    SELECT_TAB_PROMPT: "Select a tab to begin.",
    COUNTDOWN_SUFFIX: "remaining (Auto-archives when timer hits zero)",
    EDITING_BADGE: "🟢 Editing",
    READ_ONLY_BADGE: "🔒 Read-Only (Another Device)",
    TAKE_CONTROL_BTN: "Take Control",
  },
  SIDEBAR: {
    WORKSPACE_TITLE: "Current Workspace",
    SAVED_SHEETS_TITLE: "Saved Sheets",
    ARCHIVED_SHEETS_TITLE: "Archived Sheets (Read-Only)",
    NO_ACTIVE_SHEET: "No active sheet.",
    NO_ARCHIVED_SHEETS: "No archived sheets.",
    NEW_CAT_PLACEHOLDER: "Folder name...",
    NEW_CAT_BTN: "+ New Category",
    ADD_BTN: "Add",
    CANCEL_BTN: "Cancel",
    EMPTY_FOLDER: "Empty",
    ACTIVE_USER: "Active User",
    LOGOUT_BTN: "Logout",
    SYNC_ROLES_BTN: "🔄",
    FILES_TITLE: "Workspace Drive",
    NO_FILES: "No files shared.",
    UPLOAD_DRAG_PROMPT: "Drag & drop files here or click to browse",
    UPLOADING: "Uploading...",
  },
  MODALS: {
    SAVE_LIVE: {
      TITLE: "Save Live Clipboard Workspace",
      TITLE_LABEL: "Sheet Title",
      TITLE_PLACEHOLDER: "e.g. Daily Snippets",
      CAT_LABEL: "Folder Category",
      CAT_NONE: "None (Uncategorized)",
      METHOD_LABEL: "Save Method",
      METHOD_EDITABLE_TITLE: "Save Editable",
      METHOD_EDITABLE_DESC: "Allows future editing",
      METHOD_ARCHIVE_TITLE: "Archive (Read-Only)",
      METHOD_ARCHIVE_DESC: "Cannot edit directly",
    },
    CONFLICT: {
      TITLE: "⚠️ Concurrency Conflict",
      DESCRIPTION:
        "This saved sheet was modified on another device after you opened it. Red indicates deleted lines on server; Green indicates your added lines.",
      INCOMING_HEADER: "INCOMING (SERVER VERSION)",
      OUTGOING_HEADER: "OUTGOING (YOUR VERSION)",
    },
    ARCHIVE: {
      TITLE: "📦 Archived Clipboard (Read-Only)",
      TITLE_LABEL: "Title:",
      INSTRUCTION:
        "To edit this content, load it into your live workspace and save it as a new editable sheet.",
    },
    INVITE: {
      TITLE: "Manage Workspace Members",
      MEMBER_LIST_HEADER: "Current Members",
      ADD_MEMBER_LABEL: "Invite Member by Username",
      ADD_MEMBER_PLACEHOLDER: "e.g. johndoe",
      INVITE_BTN: "Invite",
      NO_MEMBERS: "No members found.",
      MAINTAINER_BADGE: "Maintainer",
      MEMBER_BADGE: "Member",
    },
  },
  ADMIN: {
    TITLE: "⚙️ Admin Control Panel",
    SUBTITLE:
      "System authority dashboard for database tables, roles, and workspaces.",
    TABS: {
      DB_EXPLORER: "📁 DB Explorer",
      USERS_ROLES: "👥 Users & Roles",
      WORKSPACES: "💼 Workspaces",
    },
    DB: {
      SELECT_TABLE: "Select a Database Table:",
      NO_DATA: "No rows found in this table.",
      PAGE_INFO: (page, total) => `Page ${page}`,
    },
    USERS: {
      EDIT_ROLES_TITLE: (user) => `Edit Roles for: ${user}`,
      ROLES_LIST_HEADER: "Current Assigned Roles",
      ADD_ROLE_HEADER: "Add New Workspace Access",
      WORKSPACE_LABEL: "Select Workspace",
      ROLE_LABEL: "Select Access Level",
      SAVE_ROLES_BTN: "Save User Roles",
    },
    WORKSPACES: {
      CREATE_TITLE: "Create New Workspace",
      CREATE_OWNER_LABEL: "Select Owner / Maintainer",
      ADD_MEMBER_TITLE: "Add User to Workspace",
    },
  },
};
