export const HEADINGS = {
  APP_TITLE: 'SyncPad',
  APP_VERSION: 'v1.0',
  AUTH: {
    LOGIN_TITLE: 'SyncPad Login',
    REGISTER_TITLE: 'SyncPad Register',
    SUBTITLE: 'Seamless cross-device clipboard sync',
    LOADING: 'Restoring session...',
  },
  DASHBOARD: {
    LIVE_SHEET_TAB: '⚡ Live Sheet',
    INITIALIZING_LIVE: 'Initializing Live Space...',
    SELECT_TAB_PROMPT: 'Select a tab to begin.',
    COUNTDOWN_SUFFIX: 'remaining (Auto-archives when timer hits zero)',
    EDITING_BADGE: '🟢 Editing',
    READ_ONLY_BADGE: '🔒 Read-Only (Another Device)',
    TAKE_CONTROL_BTN: 'Take Control',
  },
  SIDEBAR: {
    WORKSPACE_TITLE: 'Current Workspace',
    SAVED_SHEETS_TITLE: 'Saved Sheets',
    ARCHIVED_SHEETS_TITLE: 'Archived Sheets (Read-Only)',
    NO_ACTIVE_SHEET: 'No active sheet.',
    NO_ARCHIVED_SHEETS: 'No archived sheets.',
    NEW_CAT_PLACEHOLDER: 'Folder name...',
    NEW_CAT_BTN: '+ New Category',
    ADD_BTN: 'Add',
    CANCEL_BTN: 'Cancel',
    EMPTY_FOLDER: 'Empty',
    ACTIVE_USER: 'Active User',
    LOGOUT_BTN: 'Logout',
  },
  MODALS: {
    SAVE_LIVE: {
      TITLE: 'Save Live Clipboard Workspace',
      TITLE_LABEL: 'Sheet Title',
      TITLE_PLACEHOLDER: 'e.g. Daily Snippets',
      CAT_LABEL: 'Folder Category',
      CAT_NONE: 'None (Uncategorized)',
      METHOD_LABEL: 'Save Method',
      METHOD_EDITABLE_TITLE: 'Save Editable',
      METHOD_EDITABLE_DESC: 'Allows future editing',
      METHOD_ARCHIVE_TITLE: 'Archive (Read-Only)',
      METHOD_ARCHIVE_DESC: 'Cannot edit directly',
    },
    CONFLICT: {
      TITLE: '⚠️ Concurrency Conflict',
      DESCRIPTION: 'This saved sheet was modified on another device after you opened it. Red indicates deleted lines on server; Green indicates your added lines.',
      INCOMING_HEADER: 'INCOMING (SERVER VERSION)',
      OUTGOING_HEADER: 'OUTGOING (YOUR VERSION)',
    },
    ARCHIVE: {
      TITLE: '📦 Archived Clipboard (Read-Only)',
      TITLE_LABEL: 'Title:',
      INSTRUCTION: 'To edit this content, load it into your live workspace and save it as a new editable sheet.',
    },
  },
};
